In [2]:
# k-means Clustering
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("Downloads/student-scores.csv")
df

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Alan,Reynolds,alan.reynolds.1996@gslingacademy.com,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82
1996,1997,Thomas,Gilbert,thomas.gilbert.1997@gslingacademy.com,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73
1997,1998,Madison,Cross,madison.cross.1998@gslingacademy.com,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78
1998,1999,Brittany,Compton,brittany.compton.1999@gslingacademy.com,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75
1999,2000,Natalie,Smith,natalie.smith.2000@gslingacademy.com,female,False,5,False,27,Accountant,82,99,91,69,83,93,100

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          2000 non-null   int64
 1   first_name                  2000 non-null   object
 2   last_name                   2000 non-null   object
 3   email                       2000 non-null   object
 4   gender                      2000 non-null   object
 5   part_time_job               2000 non-null   bool
 6   absence_days                2000 non-null   int64
 7   extracurricular_activities  2000 non-null   bool
 8   weekly_self_study_hours     2000 non-null   int64
 9   career_aspiration           2000 non-null   object
 10  math_score                  2000 non-null   int64
 11  history_score               2000 non-null   int64
 12  physics_score               2000 non-null   int64
 13  chemistry_score             2000 non-null   int64
 14  biology_score               2000 non-null   int64
 15  english_score               2000 non-null   int64
 16  geography_score             2000 non-null   int64
dtypes: bool(2), int64(10), object(5)
memory usage: 238.4+ KB

In [5]:
df.head()

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76

In [6]:
df.tail()

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
1995,1996,Alan,Reynolds,alan.reynolds.1996@gslingacademy.com,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82
1996,1997,Thomas,Gilbert,thomas.gilbert.1997@gslingacademy.com,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73
1997,1998,Madison,Cross,madison.cross.1998@gslingacademy.com,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78
1998,1999,Brittany,Compton,brittany.compton.1999@gslingacademy.com,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75
1999,2000,Natalie,Smith,natalie.smith.2000@gslingacademy.com,female,False,5,False,27,Accountant,82,99,91,69,83,93,100

In [7]:
df.isnull().sum()

id                            0
first_name                    0
last_name                     0
email                         0
gender                        0
part_time_job                 0
absence_days                  0
extracurricular_activities    0
weekly_self_study_hours       0
career_aspiration             0
math_score                    0
history_score                 0
physics_score                 0
chemistry_score               0
biology_score                 0
english_score                 0
geography_score               0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'part_time_job',
       'absence_days', 'extracurricular_activities', 'weekly_self_study_hours',
       'career_aspiration', 'math_score', 'history_score', 'physics_score',
       'chemistry_score', 'biology_score', 'english_score', 'geography_score'],
      dtype='object')

In [11]:
# let grp into 3 clusters
# 1. High performance- Topper
# 2. Average Performance - Average
# 3. Below Average Performance - Poor or Slow Learner


# x=> features like avg score= sum of ('math_score', 'history_score', 'physics_score',
#        'chemistry_score', 'biology_score', 'english_score', 'geography_score')
# y=> feature like  'weekly_self_study_hours'

In [14]:
subjects=['math_score', 'history_score', 'physics_score',
       'chemistry_score', 'biology_score', 'english_score', 'geography_score']

df['avg_score']=df[subjects].mean(axis=1)

In [25]:
x=df[['avg_score','weekly_self_study_hours']]

In [26]:
model=KMeans(n_clusters=3,random_state=34)

In [27]:
model.fit(x)

KMeans(n_clusters=3, random_state=34)

In [28]:
labels=model.labels_
centroid=model.cluster_centers_

In [31]:
 # let get input from user to find avg_score for new student 
math = float(input("Enter Math Marks: "))
history = float(input("Enter History Marks: "))
physics = float(input("Enter Physics Marks: "))
chemistry = float(input("Enter Chemistry Marks: "))
biology = float(input("Enter Biology Marks: "))
english = float(input("Enter English Marks: "))
geography = float(input("Enter Geography Marks: "))

study_hours = float(input("Enter Weekly Self Study Hours: "))

Enter Math Marks:  89
Enter History Marks:  90
Enter Physics Marks:  90
Enter Chemistry Marks:  78
Enter Biology Marks:  80
Enter English Marks:  90
Enter Geography Marks:  100
Enter Weekly Self Study Hours:  22

In [32]:
average = (
    math +
    history +
    physics +
    chemistry +
    biology +
    english +
    geography
) / 7

In [37]:
# prediction of performance of new student
newstudent=[[average,study_hours]]
clusters=model.predict(newstudent)

C:\Users\ELCOT\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(

In [38]:
print("Prediction Result: ",clusters[0])

Prediction Result:  0

In [39]:
if clusters[0]==0:
    print("Category :Poor Performance! Need Improvement!")
elif clusters[0]==1:
    print("Category : Average Performance!")
else:
    print("Category : Excellent Performance")

Category :Poor Performance! Need Improvement!

In [46]:
# to anlayze clusters, use model.clusters_center
print(model.cluster_centers_)
# (average,study_hours)

[[80.98677249 17.99691358]
 [84.5111673  31.4719764 ]
 [77.42242476  3.72551929]]

In [47]:
# to know centroids over k=3
print(model.labels_)

# model.labels_ answers: "Which cluster did each training student go into?"

[1 1 0 ... 0 2 1]

In [ ]:
# =============================STUDENT PERFORMANCE PREDICTION BY KMEANS COMPLETED SUCCESSFULLY==============================