In [10]:
import pandas as pd
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.read_csv("/content/patient_churn_dataset.csv")
df

,PatientID,Age,Gender,State,Tenure_Months,Specialty,Insurance_Type,Visits_Last_Year,Missed_Appointments,Days_Since_Last_Visit,...,Overall_Satisfaction,Wait_Time_Satisfaction,Staff_Satisfaction,Provider_Rating,Avg_Out_Of_Pocket_Cost,Billing_Issues,Portal_Usage,Referrals_Made,Distance_To_Facility_Miles,Churned
0,C20000,41,Female,PA,62,Pediatrics,Medicaid,1,0,564,...,3.5,4.9,3.8,4.2,306,0,0,3,21.4,1
1,C20001,43,Female,GA,44,Internal Medicine,Self-Pay,7,4,254,...,2.6,3.1,4.7,4.3,1851,0,0,0,47.6,1
2,C20002,21,Male,MI,120,Internal Medicine,Medicaid,15,5,89,...,1.6,4.4,2.1,4.7,391,0,0,2,7.1,0
3,C20003,65,Male,FL,118,General Practice,Private,10,3,135,...,2.6,4.3,4.3,4.9,808,0,0,0,11.6,1
4,C20004,18,Female,CA,70,Cardiology,Medicaid,5,4,696,...,2.2,4.0,4.1,4.4,866,0,0,0,10.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,C21995,31,Male,NC,78,Internal Medicine,Medicare,8,2,180,...,3.9,1.8,2.4,2.9,268,0,1,0,42.6,1
1996,C21996,45,Female,GA,69,Internal Medicine,Private,6,4,352,...,4.2,2.8,3.5,4.6,1257,1,0,3,15.4,1
1997,C21997,37,Male,NC,91,Family Medicine,Medicare,9,4,494,...,3.9,2.7,3.0,2.7,50,0,1,3,2.6,0
1998,C21998,69,Female,NY,5,Internal Medicine,Private,3,0,315,...,1.7,3.2,3.6,4.2,848,0,0,1,38.8,1
1999,C21999,63,Female,NC,69,Family Medicine,Private,6,2,675,...,2.3,3.4,4.0,4.9,1310,0,0,1,48.2,1

In [4]:
df.head()

,PatientID,Age,Gender,State,Tenure_Months,Specialty,Insurance_Type,Visits_Last_Year,Missed_Appointments,Days_Since_Last_Visit,...,Overall_Satisfaction,Wait_Time_Satisfaction,Staff_Satisfaction,Provider_Rating,Avg_Out_Of_Pocket_Cost,Billing_Issues,Portal_Usage,Referrals_Made,Distance_To_Facility_Miles,Churned
0,C20000,41,Female,PA,62,Pediatrics,Medicaid,1,0,564,...,3.5,4.9,3.8,4.2,306,0,0,3,21.4,1
1,C20001,43,Female,GA,44,Internal Medicine,Self-Pay,7,4,254,...,2.6,3.1,4.7,4.3,1851,0,0,0,47.6,1
2,C20002,21,Male,MI,120,Internal Medicine,Medicaid,15,5,89,...,1.6,4.4,2.1,4.7,391,0,0,2,7.1,0
3,C20003,65,Male,FL,118,General Practice,Private,10,3,135,...,2.6,4.3,4.3,4.9,808,0,0,0,11.6,1
4,C20004,18,Female,CA,70,Cardiology,Medicaid,5,4,696,...,2.2,4.0,4.1,4.4,866,0,0,0,10.3,1

In [5]:
df.tail()

,PatientID,Age,Gender,State,Tenure_Months,Specialty,Insurance_Type,Visits_Last_Year,Missed_Appointments,Days_Since_Last_Visit,...,Overall_Satisfaction,Wait_Time_Satisfaction,Staff_Satisfaction,Provider_Rating,Avg_Out_Of_Pocket_Cost,Billing_Issues,Portal_Usage,Referrals_Made,Distance_To_Facility_Miles,Churned
1995,C21995,31,Male,NC,78,Internal Medicine,Medicare,8,2,180,...,3.9,1.8,2.4,2.9,268,0,1,0,42.6,1
1996,C21996,45,Female,GA,69,Internal Medicine,Private,6,4,352,...,4.2,2.8,3.5,4.6,1257,1,0,3,15.4,1
1997,C21997,37,Male,NC,91,Family Medicine,Medicare,9,4,494,...,3.9,2.7,3.0,2.7,50,0,1,3,2.6,0
1998,C21998,69,Female,NY,5,Internal Medicine,Private,3,0,315,...,1.7,3.2,3.6,4.2,848,0,0,1,38.8,1
1999,C21999,63,Female,NC,69,Family Medicine,Private,6,2,675,...,2.3,3.4,4.0,4.9,1310,0,0,1,48.2,1

In [6]:
df.isnull().sum()

PatientID                     0
Age                           0
Gender                        0
State                         0
Tenure_Months                 0
Specialty                     0
Insurance_Type                0
Visits_Last_Year              0
Missed_Appointments           0
Days_Since_Last_Visit         0
Last_Interaction_Date         0
Overall_Satisfaction          0
Wait_Time_Satisfaction        0
Staff_Satisfaction            0
Provider_Rating               0
Avg_Out_Of_Pocket_Cost        0
Billing_Issues                0
Portal_Usage                  0
Referrals_Made                0
Distance_To_Facility_Miles    0
Churned                       0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PatientID                   2000 non-null   object
 1   Age                         2000 non-null   int64
 2   Gender                      2000 non-null   object
 3   State                       2000 non-null   object
 4   Tenure_Months               2000 non-null   int64
 5   Specialty                   2000 non-null   object
 6   Insurance_Type              2000 non-null   object
 7   Visits_Last_Year            2000 non-null   int64
 8   Missed_Appointments         2000 non-null   int64
 9   Days_Since_Last_Visit       2000 non-null   int64
 10  Last_Interaction_Date       2000 non-null   object
 11  Overall_Satisfaction        2000 non-null   float64
 12  Wait_Time_Satisfaction      2000 non-null   float64
 13  Staff_Satisfaction          2000 non-null   float64
 14  Provider_Rating             2000 non-null   float64
 15  Avg_Out_Of_Pocket_Cost      2000 non-null   int64
 16  Billing_Issues              2000 non-null   int64
 17  Portal_Usage                2000 non-null   int64
 18  Referrals_Made              2000 non-null   int64
 19  Distance_To_Facility_Miles  2000 non-null   float64
 20  Churned                     2000 non-null   int64
dtypes: float64(5), int64(10), object(6)
memory usage: 328.3+ KB

In [11]:
df.columns

Index(['PatientID', 'Age', 'Gender', 'State', 'Tenure_Months', 'Specialty',
       'Insurance_Type', 'Visits_Last_Year', 'Missed_Appointments',
       'Days_Since_Last_Visit', 'Last_Interaction_Date',
       'Overall_Satisfaction', 'Wait_Time_Satisfaction', 'Staff_Satisfaction',
       'Provider_Rating', 'Avg_Out_Of_Pocket_Cost', 'Billing_Issues',
       'Portal_Usage', 'Referrals_Made', 'Distance_To_Facility_Miles',
       'Churned'],
      dtype='object')

In [40]:
#let take numeric inputs
#for bernoulli NB - inputs can be numeric or text --> main thing that particular word or number present or not
df['Missed'] = (df['Missed_Appointments'] > 0).astype(int)

df['Long_Gap'] = (df['Days_Since_Last_Visit'] >= 180).astype(int)

df['Low_Satisfaction'] = (df['Overall_Satisfaction'] <= 2).astype(int)

In [49]:
# df.head()

x=df[['Missed','Long_Gap','Low_Satisfaction']]
y=df['Churned']
df.columns

Index(['PatientID', 'Age', 'Gender', 'State', 'Tenure_Months', 'Specialty',
       'Insurance_Type', 'Visits_Last_Year', 'Missed_Appointments',
       'Days_Since_Last_Visit', 'Last_Interaction_Date',
       'Overall_Satisfaction', 'Wait_Time_Satisfaction', 'Staff_Satisfaction',
       'Provider_Rating', 'Avg_Out_Of_Pocket_Cost', 'Billing_Issues',
       'Portal_Usage', 'Referrals_Made', 'Distance_To_Facility_Miles',
       'Churned', 'Missed', 'Long_Gap', 'Low_Satisfaction', 'Billing',
       'Portal'],
      dtype='object')

In [50]:
model=BernoulliNB()


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model.fit(x_train,y_train)

le=LabelEncoder()

y_pred=model.predict(x_test)

acc=accuracy_score(y_test,y_pred)

print("Accuracy: ",acc*100,"%")

Accuracy:  73.5 %

In [59]:
le.fit(["No", "Yes"])

missed = input("Is appointment missed? (Yes/No): ")
Long_Gap = input("Is there a long gap? (Yes/No): ")
Low_Satisfaction = input("Is satisfaction low? (Yes/No): ")

# Convert Yes/No → 0/1
missed = le.fit_transform([missed])[0]
Long_Gap = le.fit_transform([Long_Gap])[0]
Low_Satisfaction = le.fit_transform([Low_Satisfaction])[0]

prediction=model.predict([[missed,Long_Gap,Low_Satisfaction]])
print("Predicted Result",le.fit_transform(prediction)[0])

if prediction[0] == 1:
    print("Predicted Result: Patient will CHURN")
else:
    print("Predicted Result: Patient will NOT CHURN")

Is appointment missed? (Yes/No): yes
Is there a long gap? (Yes/No): yes
Is satisfaction low? (Yes/No): yes
Predicted Result 0
Predicted Result: Patient will CHURN

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(