In [1]:
import numpy as np
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA

In [3]:
df=pd.read_csv("/calendar.csv")
df

           date  year  month  day  week  day_of_week
0    2023-01-01  2023      1    1    52            6
1    2023-01-02  2023      1    2     1            0
2    2023-01-03  2023      1    3     1            1
3    2023-01-04  2023      1    4     1            2
4    2023-01-05  2023      1    5     1            3
..          ...   ...    ...  ...   ...          ...
726  2024-12-27  2024     12   27    52            4
727  2024-12-28  2024     12   28    52            5
728  2024-12-29  2024     12   29    52            6
729  2024-12-30  2024     12   30     1            0
730  2024-12-31  2024     12   31     1            1

[731 rows x 6 columns]

In [4]:
df.head()

         date  year  month  day  week  day_of_week
0  2023-01-01  2023      1    1    52            6
1  2023-01-02  2023      1    2     1            0
2  2023-01-03  2023      1    3     1            1
3  2023-01-04  2023      1    4     1            2
4  2023-01-05  2023      1    5     1            3

In [5]:
df.tail()

           date  year  month  day  week  day_of_week
726  2024-12-27  2024     12   27    52            4
727  2024-12-28  2024     12   28    52            5
728  2024-12-29  2024     12   29    52            6
729  2024-12-30  2024     12   30     1            0
730  2024-12-31  2024     12   31     1            1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         731 non-null    object
 1   year         731 non-null    int64
 2   month        731 non-null    int64
 3   day          731 non-null    int64
 4   week         731 non-null    int64
 5   day_of_week  731 non-null    int64
dtypes: int64(5), object(1)
memory usage: 34.4+ KB

In [7]:
df.isnull().sum()

date           0
year           0
month          0
day            0
week           0
day_of_week    0
dtype: int64

In [8]:

df.columns

Index(['date', 'year', 'month', 'day', 'week', 'day_of_week'], dtype='object')

In [14]:
df['Date']=pd.to_datetime(df['date'])
df['Date']

0     2023-01-01
1     2023-01-02
2     2023-01-03
3     2023-01-04
4     2023-01-05
         ...
726   2024-12-27
727   2024-12-28
728   2024-12-29
729   2024-12-30
730   2024-12-31
Name: Date, Length: 731, dtype: datetime64[ns]

In [17]:
df=df.sort_values("date")
df

          date  year  month  day  week  day_of_week       Date
0   2023-01-01  2023      1    1    52            6 2023-01-01
1   2023-01-02  2023      1    2     1            0 2023-01-02
2   2023-01-03  2023      1    3     1            1 2023-01-03
3   2023-01-04  2023      1    4     1            2 2023-01-04
4   2023-01-05  2023      1    5     1            3 2023-01-05
..         ...   ...    ...  ...   ...          ...        ...
726 2024-12-27  2024     12   27    52            4 2024-12-27
727 2024-12-28  2024     12   28    52            5 2024-12-28
728 2024-12-29  2024     12   29    52            6 2024-12-29
729 2024-12-30  2024     12   30     1            0 2024-12-30
730 2024-12-31  2024     12   31     1            1 2024-12-31

[731 rows x 7 columns]

In [19]:
data=df['day_of_week']
# df.head()

In [25]:
model=ARIMA(data,order=[6,1,0])
model.fit=model.fit()

pred=model.fit.forecast(steps=7)

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'

In [26]:
print("Forecasting result for chocolate Sales:")
print("Day 1:",pred.iloc[0])
print("Day 2:",pred.iloc[1])
print("Day 3:",pred.iloc[2])
print("Day 4:",pred.iloc[3])
print("Day 5:",pred.iloc[4])
print("Day 6:",pred.iloc[5])
print("Day 7:",pred.iloc[6])

Forecasting result for chocolate Sales:
Day 1: 1.0000006524286122
Day 2: 1.0000009420914546
Day 3: 1.000001376842591
Day 4: 1.0000019562609557
Day 5: 1.0000026468014123
Day 6: 1.0000025077696875
Day 7: 1.0000025077692605

In [31]:
print(pred)

731    1.000001
732    1.000001
733    1.000001
734    1.000002
735    1.000003
736    1.000003
737    1.000003
Name: predicted_mean, dtype: float64