In [ ]:
import pandas as pd

# multinomial naive bayes import
from sklearn.naive_bayes import MultinomialNB

from sklearn.feature_extraction.text import CountVectorizer

#output : labels (spam/non-spam) --> spam=1 , non-spam=0

from sklearn.preprocessing import LabelEncoder

In [ ]:
# data
df = pd.read_csv("/content/dataset.csv")
df

                                                  email  category
0     URL: http://www.newsisfree.com/click/-1,817167...  not-spam
1     On Thu, 19 Sep 2002, Bill Stoddard wrote:\n\n-...  not-spam
2     Dan Kohn <dan@dankohn.com> writes:\n\n\n\n> Gu...  not-spam
3     wintermute wrote:\n\n>>Anyone know where in Ir...  not-spam
4     I attended the same conference, and was impres...  not-spam
...                                                 ...       ...
3791  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Tr...      spam
3792  <html>\n\n<HEAD> \n\n<TITLE>creditfix</TITLE> ...      spam
3793  Hello:\n\n\n\nAre you satisfied with your ISP?...      spam
3794  <html><HEAD><TITLE>creditfix</TITLE> \n\n</HEA...      spam
3795  <HTML><HEAD></HEAD><BODY><b><FONT SIZE=3D4>In ...      spam

[3796 rows x 2 columns]

In [ ]:
df.head()

                                               email  category
0  URL: http://www.newsisfree.com/click/-1,817167...  not-spam
1  On Thu, 19 Sep 2002, Bill Stoddard wrote:\n\n-...  not-spam
2  Dan Kohn <dan@dankohn.com> writes:\n\n\n\n> Gu...  not-spam
3  wintermute wrote:\n\n>>Anyone know where in Ir...  not-spam
4  I attended the same conference, and was impres...  not-spam

In [ ]:
df.tail()

                                                  email category
3791  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Tr...     spam
3792  <html>\n\n<HEAD> \n\n<TITLE>creditfix</TITLE> ...     spam
3793  Hello:\n\n\n\nAre you satisfied with your ISP?...     spam
3794  <html><HEAD><TITLE>creditfix</TITLE> \n\n</HEA...     spam
3795  <HTML><HEAD></HEAD><BODY><b><FONT SIZE=3D4>In ...     spam

In [ ]:
df.isnull().sum()

email       0
category    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3796 entries, 0 to 3795
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   email     3796 non-null   object
 1   category  3796 non-null   object
dtypes: object(2)
memory usage: 59.4+ KB

In [11]:
# input and output

x=df['email']#input
y=df['category']#output

model=MultinomialNB()

le=LabelEncoder()

#le.fit_transform --> means fit is for train(learn from past data) and transform convert text into number
y_val=le.fit_transform(y)

#convert y labels into values


#count vectorizer - to count each word in input(x)
vector=CountVectorizer()
x_val=vector.fit_transform(x)
#count words in x column



#model created

model.fit(x_val,y_val)

MultinomialNB()

In [ ]:
#testing
while True:
  email_user=input("compose your mail here: ")

  test_email=vector.transform([email_user])


  prediction=model.predict(test_email)
  print("Predicted Email is :",le.inverse_transform(prediction)[0])

print("Predicted Email is :",prediction[0])

#spam - 1 and non-spam - 0

compose your mail here: hello free offer
Predicted Email is : spam
compose your mail here: project meeting on monday
Predicted Email is : not-spam
compose your mail here: referral hiring
Predicted Email is : spam
compose your mail here: congratulations you are hired
Predicted Email is : spam
compose your mail here: you are fired
Predicted Email is : not-spam
compose your mail here: sorry you are fired
Predicted Email is : not-spam
compose your mail here: sorry you are hired
Predicted Email is : not-spam