In [6]:
import pandas as pd

# BernoulliNB -- it simply check whether word present or not

#data will be take as one hot encoding --> if data is present , return 1
                                          #  otherwise return 0

from sklearn.naive_bayes import BernoulliNB

from sklearn.model_selection import train_test_split

# accuracy
from sklearn.metrics import accuracy_score

In [7]:
df=pd.read_csv("/content/patient_churn_dataset.csv")
df

,PatientID,Age,Gender,State,Tenure_Months,Specialty,Insurance_Type,Visits_Last_Year,Missed_Appointments,Days_Since_Last_Visit,...,Overall_Satisfaction,Wait_Time_Satisfaction,Staff_Satisfaction,Provider_Rating,Avg_Out_Of_Pocket_Cost,Billing_Issues,Portal_Usage,Referrals_Made,Distance_To_Facility_Miles,Churned
0,C20000,41,Female,PA,62,Pediatrics,Medicaid,1,0,564,...,3.5,4.9,3.8,4.2,306,0,0,3,21.4,1
1,C20001,43,Female,GA,44,Internal Medicine,Self-Pay,7,4,254,...,2.6,3.1,4.7,4.3,1851,0,0,0,47.6,1
2,C20002,21,Male,MI,120,Internal Medicine,Medicaid,15,5,89,...,1.6,4.4,2.1,4.7,391,0,0,2,7.1,0
3,C20003,65,Male,FL,118,General Practice,Private,10,3,135,...,2.6,4.3,4.3,4.9,808,0,0,0,11.6,1
4,C20004,18,Female,CA,70,Cardiology,Medicaid,5,4,696,...,2.2,4.0,4.1,4.4,866,0,0,0,10.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,C21995,31,Male,NC,78,Internal Medicine,Medicare,8,2,180,...,3.9,1.8,2.4,2.9,268,0,1,0,42.6,1
1996,C21996,45,Female,GA,69,Internal Medicine,Private,6,4,352,...,4.2,2.8,3.5,4.6,1257,1,0,3,15.4,1
1997,C21997,37,Male,NC,91,Family Medicine,Medicare,9,4,494,...,3.9,2.7,3.0,2.7,50,0,1,3,2.6,0
1998,C21998,69,Female,NY,5,Internal Medicine,Private,3,0,315,...,1.7,3.2,3.6,4.2,848,0,0,1,38.8,1
1999,C21999,63,Female,NC,69,Family Medicine,Private,6,2,675,...,2.3,3.4,4.0,4.9,1310,0,0,1,48.2,1

In [8]:
df.head()

,PatientID,Age,Gender,State,Tenure_Months,Specialty,Insurance_Type,Visits_Last_Year,Missed_Appointments,Days_Since_Last_Visit,...,Overall_Satisfaction,Wait_Time_Satisfaction,Staff_Satisfaction,Provider_Rating,Avg_Out_Of_Pocket_Cost,Billing_Issues,Portal_Usage,Referrals_Made,Distance_To_Facility_Miles,Churned
0,C20000,41,Female,PA,62,Pediatrics,Medicaid,1,0,564,...,3.5,4.9,3.8,4.2,306,0,0,3,21.4,1
1,C20001,43,Female,GA,44,Internal Medicine,Self-Pay,7,4,254,...,2.6,3.1,4.7,4.3,1851,0,0,0,47.6,1
2,C20002,21,Male,MI,120,Internal Medicine,Medicaid,15,5,89,...,1.6,4.4,2.1,4.7,391,0,0,2,7.1,0
3,C20003,65,Male,FL,118,General Practice,Private,10,3,135,...,2.6,4.3,4.3,4.9,808,0,0,0,11.6,1
4,C20004,18,Female,CA,70,Cardiology,Medicaid,5,4,696,...,2.2,4.0,4.1,4.4,866,0,0,0,10.3,1

In [9]:
df.tail()

,PatientID,Age,Gender,State,Tenure_Months,Specialty,Insurance_Type,Visits_Last_Year,Missed_Appointments,Days_Since_Last_Visit,...,Overall_Satisfaction,Wait_Time_Satisfaction,Staff_Satisfaction,Provider_Rating,Avg_Out_Of_Pocket_Cost,Billing_Issues,Portal_Usage,Referrals_Made,Distance_To_Facility_Miles,Churned
1995,C21995,31,Male,NC,78,Internal Medicine,Medicare,8,2,180,...,3.9,1.8,2.4,2.9,268,0,1,0,42.6,1
1996,C21996,45,Female,GA,69,Internal Medicine,Private,6,4,352,...,4.2,2.8,3.5,4.6,1257,1,0,3,15.4,1
1997,C21997,37,Male,NC,91,Family Medicine,Medicare,9,4,494,...,3.9,2.7,3.0,2.7,50,0,1,3,2.6,0
1998,C21998,69,Female,NY,5,Internal Medicine,Private,3,0,315,...,1.7,3.2,3.6,4.2,848,0,0,1,38.8,1
1999,C21999,63,Female,NC,69,Family Medicine,Private,6,2,675,...,2.3,3.4,4.0,4.9,1310,0,0,1,48.2,1

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PatientID                   2000 non-null   object
 1   Age                         2000 non-null   int64
 2   Gender                      2000 non-null   object
 3   State                       2000 non-null   object
 4   Tenure_Months               2000 non-null   int64
 5   Specialty                   2000 non-null   object
 6   Insurance_Type              2000 non-null   object
 7   Visits_Last_Year            2000 non-null   int64
 8   Missed_Appointments         2000 non-null   int64
 9   Days_Since_Last_Visit       2000 non-null   int64
 10  Last_Interaction_Date       2000 non-null   object
 11  Overall_Satisfaction        2000 non-null   float64
 12  Wait_Time_Satisfaction      2000 non-null   float64
 13  Staff_Satisfaction          2000 non-null   float64
 14  Provider_Rating             2000 non-null   float64
 15  Avg_Out_Of_Pocket_Cost      2000 non-null   int64
 16  Billing_Issues              2000 non-null   int64
 17  Portal_Usage                2000 non-null   int64
 18  Referrals_Made              2000 non-null   int64
 19  Distance_To_Facility_Miles  2000 non-null   float64
 20  Churned                     2000 non-null   int64
dtypes: float64(5), int64(10), object(6)
memory usage: 328.3+ KB

In [12]:
# input and output features

df['missed']=(df['Missed_Appointments']>=0).astype(int)

df['day_visit']=(df['Days_Since_Last_Visit']>=180).astype(int)

# df['Days_Since_Last_Visit'].mean()
df['rating']=(df['Overall_Satisfaction']>=2).astype(int)

In [13]:
x=df[['missed','day_visit','rating']]
y=df['Churned']

# input and output features

In [15]:
# train and test split
x_train,x_test,y_train,y_test=train_test_split(x,y)
model=BernoulliNB()
model.fit(x_train,y_train)

BernoulliNB()

In [16]:
# accuracy
y_pred=model.predict(x_test)
acc=accuracy_score(y_test,y_pred)

print("Accuracy:",acc)

Accuracy: 0.696

In [17]:
# user inputs
# missed','day_visit','rating'

missed=int(input("Enter missed apointments:"))
day_visit=int(input("Enter day visits:"))
rating=int(input("Enter rating:"))

user=model.predict([[missed,day_visit,rating]])

if user==1:
  print("Churned")
else:
  print("Not Churned")
#  note:
#  (Binary form data will be taken and predict category)
# inputs: present or not? then it takes value as 0 or 1 and provide predicted result

Enter missed apointments:1
Enter day visits:0
Enter rating:0
Churned

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(