In [1]:
# 1. import libr
import pandas as pd
import numpy as np
import folium
import webbrowser
import os

from sklearn.cluster import DBSCAN
from IPython.display import display

In [2]:
df=pd.read_csv("/content/NYPD_Arrest_Data_2023.csv")
df

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
0,261209118,01/01/2023,109,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,K,77,0,45-64,F,BLACK,999335,186085,40.677426,-73.945615
1,262984267,02/03/2023,515,"CONTROLLED SUBSTANCE,SALE 3",117.0,DANGEROUS DRUGS,PL 2203901,F,K,73,0,25-44,M,BLACK,1009318,178259,40.655923,-73.909650
2,263664549,02/15/2023,105,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,K,62,0,25-44,M,WHITE,982272,158771,40.602468,-74.007120
3,261345231,01/04/2023,105,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,M,32,0,25-44,M,BLACK,999899,238684,40.821797,-73.943457
4,263536618,02/13/2023,109,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 12005WX,F,K,71,0,25-44,M,BLACK,1001437,183080,40.669175,-73.938042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170090,270955727,07/07/2023,397,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 1601002,F,B,52,0,25-44,M,BLACK,1017273,255924,40.869067,-73.880600
170091,273117887,08/18/2023,681,"CHILD, ENDANGERING WELFARE",233.0,SEX CRIMES,PL 2601001,M,B,47,0,25-44,F,BLACK,1026480,262584,40.887314,-73.847272
170092,274301006,09/13/2023,969,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL051101A,M,S,122,0,25-44,M,WHITE HISPANIC,951857,161569,40.610087,-74.116666
170093,269912233,06/15/2023,490,"STOLEN PROPERTY 3,POSSESSION",232.0,POSSESSION OF STOLEN PROPERTY,PL 1654000,M,K,62,0,25-44,M,BLACK,983469,157947,40.600204,-74.002812
170094,272045762,07/28/2023,729,"FORGERY,ETC.,UNCLASSIFIED-FELO",113.0,FORGERY,PL 1702500,F,K,84,0,18-24,M,BLACK,988491,195163,40.702353,-73.984704

In [3]:
df.head()

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
0,261209118,01/01/2023,109,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,K,77,0,45-64,F,BLACK,999335,186085,40.677426,-73.945615
1,262984267,02/03/2023,515,"CONTROLLED SUBSTANCE,SALE 3",117.0,DANGEROUS DRUGS,PL 2203901,F,K,73,0,25-44,M,BLACK,1009318,178259,40.655923,-73.909650
2,263664549,02/15/2023,105,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,K,62,0,25-44,M,WHITE,982272,158771,40.602468,-74.007120
3,261345231,01/04/2023,105,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,M,32,0,25-44,M,BLACK,999899,238684,40.821797,-73.943457
4,263536618,02/13/2023,109,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 12005WX,F,K,71,0,25-44,M,BLACK,1001437,183080,40.669175,-73.938042

In [4]:
df.tail()

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
170090,270955727,07/07/2023,397,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 1601002,F,B,52,0,25-44,M,BLACK,1017273,255924,40.869067,-73.880600
170091,273117887,08/18/2023,681,"CHILD, ENDANGERING WELFARE",233.0,SEX CRIMES,PL 2601001,M,B,47,0,25-44,F,BLACK,1026480,262584,40.887314,-73.847272
170092,274301006,09/13/2023,969,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL051101A,M,S,122,0,25-44,M,WHITE HISPANIC,951857,161569,40.610087,-74.116666
170093,269912233,06/15/2023,490,"STOLEN PROPERTY 3,POSSESSION",232.0,POSSESSION OF STOLEN PROPERTY,PL 1654000,M,K,62,0,25-44,M,BLACK,983469,157947,40.600204,-74.002812
170094,272045762,07/28/2023,729,"FORGERY,ETC.,UNCLASSIFIED-FELO",113.0,FORGERY,PL 1702500,F,K,84,0,18-24,M,BLACK,988491,195163,40.702353,-73.984704

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170095 entries, 0 to 170094
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ARREST_KEY         170095 non-null  int64
 1   ARREST_DATE        170095 non-null  object
 2   PD_CD              170095 non-null  int64
 3   PD_DESC            170095 non-null  object
 4   KY_CD              170082 non-null  float64
 5   OFNS_DESC          170095 non-null  object
 6   LAW_CODE           170095 non-null  object
 7   LAW_CAT_CD         168838 non-null  object
 8   ARREST_BORO        170095 non-null  object
 9   ARREST_PRECINCT    170095 non-null  int64
 10  JURISDICTION_CODE  170095 non-null  int64
 11  AGE_GROUP          170095 non-null  object
 12  PERP_SEX           170095 non-null  object
 13  PERP_RACE          170095 non-null  object
 14  X_COORD_CD         170095 non-null  int64
 15  Y_COORD_CD         170095 non-null  int64
 16  Latitude           170095 non-null  float64
 17  Longitude          170095 non-null  float64
dtypes: float64(3), int64(6), object(9)
memory usage: 23.4+ MB

In [6]:
df.isnull().sum()

ARREST_KEY              0
ARREST_DATE             0
PD_CD                   0
PD_DESC                 0
KY_CD                  13
OFNS_DESC               0
LAW_CODE                0
LAW_CAT_CD           1257
ARREST_BORO             0
ARREST_PRECINCT         0
JURISDICTION_CODE       0
AGE_GROUP               0
PERP_SEX                0
PERP_RACE               0
X_COORD_CD              0
Y_COORD_CD              0
Latitude                0
Longitude               0
dtype: int64

In [7]:
# let take required features for finding crimespots

df.columns

Index(['ARREST_KEY', 'ARREST_DATE', 'PD_CD', 'PD_DESC', 'KY_CD', 'OFNS_DESC',
       'LAW_CODE', 'LAW_CAT_CD', 'ARREST_BORO', 'ARREST_PRECINCT',
       'JURISDICTION_CODE', 'AGE_GROUP', 'PERP_SEX', 'PERP_RACE', 'X_COORD_CD',
       'Y_COORD_CD', 'Latitude', 'Longitude'],
      dtype='object')

In [19]:
locations=df[['Latitude', 'Longitude']].copy()

In [20]:
# convert coordinates to numeric
locations['Latitude']=pd.to_numeric(locations['Latitude'], errors='coerce')
locations['Longitude']=pd.to_numeric(locations['Longitude'], errors='coerce')

In [21]:
# let remove missing and invalid coordinates
locations=locations.dropna(subset=['Latitude', 'Longitude'])

In [22]:
locations=locations[locations['Latitude'].between(-90,90)& locations['Latitude'].between(-180,180)].copy()

In [23]:
# remove coordinates that represents (0,0)
locations = locations[~((locations['Latitude'] == 0) & (locations['Longitude'] == 0))].copy()

print("Valid Location Records: ", len(locations))

Valid Location Records:  170094

In [24]:
# convert latitude and longitude to radians
coords=np.radians(locations[['Latitude', 'Longitude']].to_numpy())

In [25]:
# apply dbscan clustering
earth_radiuskm=6371.0
radiuskm=0.5

# eps radius --> Locations within roughly 500 metres are considered neighbours.

#minsamples=10 -->core point needs at least 10 points in its neighbourhood, including itself.

model=DBSCAN(eps=radiuskm/earth_radiuskm, min_samples=1, algorithm='ball_tree', metric='haversine')
locations['Cluster']=model.fit_predict(coords)

In [26]:
# Display cluster results
cluster_ids = set(locations['Cluster'])

number_of_clusters = len(cluster_ids - {-1})
noise_count = (locations['Cluster'] == -1).sum()

print("Total clusters:", number_of_clusters)
print("Noise points:", noise_count)
print("\nCluster counts:")
print(locations['Cluster'].value_counts().sort_index())

Total clusters: 59
Noise points: 0

Cluster counts:
Cluster
0     159754
1       2210
2       6955
3        388
4        353
5         21
6         24
7         91
8         34
9          3
10        32
11         6
12         3
13        14
14        14
15         3
16         7
17        22
18         1
19         9
20         2
21         2
22         7
23         1
24         6
25         9
26         1
27        30
28         3
29         1
30        14
31         4
32        15
33         1
34         4
35         1
36         8
37         5
38         1
39         1
40         2
41         4
42         1
43         4
44         2
45         1
46         2
47         1
48         3
49         1
50         1
51         1
52         2
53         2
54         1
55         3
56         1
57         1
58         1
Name: count, dtype: int64

In [27]:
# Create the interactive Folium map
crime_map = folium.Map(location=[40.7128, -74.0060],zoom_start=11,tiles='CartoDB positron')

/usr/local/lib/python3.13/dist-packages/folium/raster_layers.py:130: UserWarning: CartoDB tiles now require an API key. Please provide one to continue using the tiles. You can request the key at https://carto.com/basemaps/apikey/.
  tiles = tiles.build_url(fill_subdomain=False, scale_factor="{r}")  # type: ignore

In [28]:
#Assign a different colour to each cluster
colors = [
    'blue', 'red', 'green', 'purple', 'orange',
    'darkred', 'cadetblue', 'darkgreen', 'pink',
    'darkblue', 'beige', 'gray'
]

In [29]:
 #Plot the arrest locations on the map
for _, row in locations.iterrows():

    cluster = int(row['Cluster'])

    if cluster == -1:
        color = 'black'
    else:
        color = colors[cluster % len(colors)]

    folium.CircleMarker(
        location=[
            row['Latitude'],
            row['Longitude']
        ],
        radius=3,
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.65,
        weight=1,
        popup=f"Cluster: {cluster}"
    ).add_to(crime_map)

In [ ]:
#Save the interactive map
map_file = os.path.abspath("dbscan_crime_hotspots.html")
crime_map.save(map_file)

print("\nMap saved at:", map_file)

In [ ]:
# display map
display(crime_map)