In [4]:
import pandas as pd

# import
from sklearn.tree import DecisionTreeClassifier

# output category

from sklearn.preprocessing import LabelEncoder

#train and test split

from sklearn.model_selection import train_test_split

#accuracy score

from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_csv("/content/drug200.csv")
df

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [5]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [6]:
df.tail()

     Age Sex      BP Cholesterol  Na_to_K   Drug
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [8]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [40]:
# input and output features



le_sex=LabelEncoder()
le_bp=LabelEncoder()
le_chol=LabelEncoder()


# convert labels into number and also fit into the model
df['sex']=le_sex.fit_transform(df['Sex'])
df['bp']=le_bp.fit_transform(df['BP'])
df['chol']=le_chol.fit_transform(df['Cholesterol'])

# df.columns
x=df[['sex','bp','chol','Age']]
y=df['Drug']

In [41]:
# model create
model=DecisionTreeClassifier()

# train and test data

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [42]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [43]:
# accuracy

y_pred=model.predict(x_test)

acc=accuracy_score(y_test,y_pred)

print("Accuracy: ",acc*100)

Accuracy:  45.0

In [50]:
# user input

# sex,bp,chol
age=int(input("Enter your Age:"))
sex=input("Enter Gender category(F or M):").upper()
bp=input("Enter BP Level(High or Low)").upper()
chol=input("Enter Cholestrol level(High or Normal)").upper()


# prediction
sex=le_sex.transform([sex])
bp=le_bp.transform([bp])
chol=le_chol.transform([chol])

# output




pred=model.predict([[sex[0],bp[0],chol[0],age]])[0]
print("Predicted Result:",pred)

Enter your Age:47
Enter Gender category(F or M):M
Enter BP Level(High or Low)low
Enter Cholestrol level(High or Normal)high
Predicted Result: drugC

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [38]:
df['Drug'].values

array(['DrugY', 'drugC', 'drugC', 'drugX', 'DrugY', 'drugX', 'DrugY',
       'drugC', 'DrugY', 'DrugY', 'drugC', 'DrugY', 'DrugY', 'DrugY',
       'drugX', 'DrugY', 'drugX', 'drugA', 'drugC', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX',
       'DrugY', 'DrugY', 'drugX', 'drugB', 'drugX', 'DrugY', 'drugX',
       'drugX', 'drugA', 'drugX', 'drugX', 'drugX', 'DrugY', 'drugB',
       'DrugY', 'drugX', 'drugX', 'drugX', 'drugA', 'drugC', 'DrugY',
       'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugB', 'drugC',
       'drugB', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugA', 'DrugY',
       'drugX', 'drugB', 'DrugY', 'drugA', 'drugX', 'DrugY', 'DrugY',
       'drugB', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'drugA',
       'DrugY', 'drugA', 'drugX', 'drugB', 'drugX', 'drugC', 'drugA',
       'drugC', 'drugB', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'drugA', 'drugA', 'drugC', 'drugX', 'DrugY',
       'drugX', 'drugX', 'DrugY', 'drugB', 'DrugY', 'drugA', 'drugX',
       'drugX', 'drugX', 'drugX', 'DrugY', 'drugX', 'drugX', 'drugA',
       'DrugY', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugB', 'DrugY',
       'DrugY', 'drugX', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugX',
       'DrugY', 'DrugY', 'drugX', 'drugB', 'drugA', 'drugB', 'drugX',
       'drugA', 'DrugY', 'drugB', 'DrugY', 'drugA', 'drugX', 'drugX',
       'drugA', 'drugX', 'drugC', 'drugA', 'drugB', 'drugX', 'drugX',
       'DrugY', 'drugC', 'drugA', 'DrugY', 'drugC', 'drugX', 'drugX',
       'drugB', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX',
       'DrugY', 'drugA', 'drugX', 'drugX', 'DrugY', 'DrugY', 'drugA',
       'DrugY', 'drugA', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX',
       'drugX', 'DrugY', 'DrugY', 'DrugY', 'drugB', 'drugA', 'DrugY',
       'DrugY', 'DrugY', 'drugA', 'DrugY', 'drugC', 'DrugY', 'drugC',
       'drugC', 'drugX', 'drugX', 'drugX'], dtype=object)